name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: |
          cd docs
          doxygen Doxyfile
          cd ..

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          enable_jekyll: false
          full_commit_message: Deploy Doxygen documentation
          
      - name: List generated files
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo "Contents of docs/html directory (if exists):"
          ls -la docs/html/ || echo "html directory not found"