name: Generate Documentation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 Pygments
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Clone m.css
        run: |
          git clone https://github.com/mosra/m.css.git

      - name: Create documentation directory
        run: mkdir -p documentation

      - name: Prepare Doxyfile
        run: |
          doxygen -g Doxyfile
          
          # Configure Doxyfile for m.css and project specifics
          sed -i 's/PROJECT_NAME.*=.*/PROJECT_NAME           = "fbgl"/g' Doxyfile
          sed -i 's/INPUT.*=.*/INPUT                  = README.md fbhl.h/g' Doxyfile
          sed -i 's/USE_MDFILE_AS_MAINPAGE.*=.*/USE_MDFILE_AS_MAINPAGE = README.md/g' Doxyfile
          sed -i 's/EXTRACT_ALL.*=.*/EXTRACT_ALL            = YES/g' Doxyfile
          sed -i 's/RECURSIVE.*=.*/RECURSIVE            = YES/g' Doxyfile
          sed -i 's/GENERATE_HTML.*=.*/GENERATE_HTML        = YES/g' Doxyfile
          sed -i 's/OUTPUT_DIRECTORY.*=.*/OUTPUT_DIRECTORY       = documentation/g' Doxyfile

      - name: Generate Documentation with m.css
        run: |
          python3 m.css/documentation/doxygen.py Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/html
          publish_branch: gh-pages