name: Generate and Deploy Doxygen Documentation with m.css

on:
  push:
    branches:
      - master  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Doxygen and Python
      - name: Install Doxygen and Python
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz python3 python3-pip

      # Step 3: Clone m.css repository
      - name: Clone m.css
        run: |
          git clone --depth 1 https://github.com/mosra/m.css.git docs/m.css

      # Step 4: Create Doxyfile
        # Ensure your Doxyfile includes the correct HTML_EXTRA_FILES configuration as mentioned above

      # Step 5: Run Doxygen
      - name: Run Doxygen
        run: doxygen Doxyfile

      # Step 6: Process HTML with m.css
      - name: Apply m.css
        run: |
          python3 docs/m.css/documentation/doxygen.py Doxyfile

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          publish_branch: gh-pages
