name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - master  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # Step 3: Ensure docs directory exists and download Doxygen Awesome files
      - name: Setup Doxygen Awesome Theme
        run: |
          mkdir -p docs
          curl -o docs/doxygen-style.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
          curl -o docs/doxygen-dark.js https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome-darkmode-toggle.js

      # Step 4: Run Doxygen using the existing Doxyfile
      - name: Run Doxygen
        run: doxygen Doxyfile

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          publish_branch: gh-pages
